run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    # Bugs & Errors
    - errcheck
    - staticcheck
    - govet
    - unused
    - gosec
    - bodyclose
    - nilerr
    
    # Code Style & Quality
    - revive       # (replaces golint)
    - gocritic     # (extensive checks)
    - ineffassign
    - misspell
    - gofmt
    - goimports
    - unconvert
    - unparam
    - nakedret
    
    # Complexity
    - gocyclo

linters-settings:
  goimports:
    local-prefixes: github.com/go-modkit/modkit
  govet:
    enable:
      - nilness
      - unusedresult
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint

issues:
  exclude-use-default: false
  exclude-dirs:
    - vendor
    - third_party
    - node_modules
    - docs
    
  # Do NOT globally exclude tests
  exclude-files:
    - ".*\\.sql\\.go" # Generated SQLC files
    - ".*\\.pb\\.go"  # Generated Proto files
    - ".*_mock\\.go"  # Mocks

  exclude-rules:
    # Relax rules for tests
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - dupl
        - funlen
        - gocyclo
        - lll
    
    # Intentional API design choices
    - path: modkit/module/module\.go
      text: "type name will be used as module.ModuleDef"
      linters:
        - revive
    
    # Test helpers that intentionally use value receivers
    - path: modkit/kernel/mod_helper_test\.go
      text: "hugeParam.*valueModule"
      linters:
        - gocritic
    
    # Standard library types passed by value
    - path: modkit/logging/logger_test\.go
      text: "hugeParam.*slog.Record"
      linters:
        - gocritic
